version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.462.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.486.0
    - 1.488.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.517.0
    - 1.520.0
    - 1.521.0
    - 1.522.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.570.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.14
  - dependency-name: "@mountainpass/waychaser"
    versions:
    - 3.0.29
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 28.0.2
    - 29.0.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: jscpd
    versions:
    - 3.3.23
    - 3.3.24
    - 3.3.25
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
  - dependency-name: swagger-ui-express
    versions:
    - 4.1.6
  - dependency-name: "@cucumber/cucumber"
    versions:
    - 7.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: eslint-plugin-standard
    versions:
    - 5.0.0
  - dependency-name: eslint-config-standard
    versions:
    - 16.0.2
